export default [
  {
    id: 1,
    postedOn: '2023-10-28',
    title: 'iOS Developer',
    company: 'Apple',
    type: 'Full Time',
    experience: 'Mid Level',
    location: 'Remote',
    skills: ["SwiftUI", "UiKit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 2,
    postedOn: '2023-10-24',
    title: "Frontend Developer",
    type: "Full time",
    location: "In-office",
    experience: "Fresher",
    company: "Amazon",
    skills: ["Javascript", "Nextjs", "Tailwind CSS"],
    job_link: "https://www.amazon.jobs/en/",
  },
  {
    id: 3,
    postedOn: '2023-11-02',
    title: "Android Developer",
    type: "Part time",
    location: "Remote",
    experience: "Senior Level",
    company: "Facebook",
    skills: ["Kotlin", "MVVM"],
    job_link: "https://facebook.com/careers",
  },
  {
    id: 4,
    postedOn: '2023-11-01',
    title: "Developer Advocate",
    type: "Contract",
    location: "Hybrid",
    experience: "Junior Level",
    company: "Netflix",
    companyUrl: "https://facebook.com",
    skills: ["web3", "Content Creation", "Community"],
    job_link: "https://jobs.netflix.com/",
  },
  {
    id: 5,
    postedOn: '2023-12-05',
    title: "Software Engineer",
    type: "Full Time",
    location: "In-office",
    experience: "Mid Level",
    company: "Google",
    skills: ["Python", "Java", "C++"],
    job_link: "https://careers.google.com/",
  },
  {
    id: 6,
    postedOn: '2023-12-10',
    title: "Data Scientist",
    type: "Full Time",
    location: "Remote",
    experience: "Senior Level",
    company: "Microsoft",
    skills: ["Machine Learning", "Statistics", "Python"],
    job_link: "https://careers.microsoft.com/",
  },
  {
    id: 7,
    postedOn: '2023-12-15',
    title: "Backend Developer",
    type: "Full Time",
    location: "In-office",
    experience: "Junior Level",
    company: "Uber",
    skills: ["Node.js", "Express", "MongoDB"],
    job_link: "https://www.uber.com/global/en/careers/",
  },
  {
    id: 8,
    postedOn: '2023-12-20',
    title: "UX/UI Designer",
    type: "Full Time",
    location: "Hybrid",
    experience: "Mid Level",
    company: "Adobe",
    skills: ["UI Design", "Prototyping", "Adobe XD"],
    job_link: "https://www.adobe.com/careers.html",
  },
  {
    id: 9,
    postedOn: '2023-12-25',
    title: "Product Manager",
    type: "Full Time",
    location: "Remote",
    experience: "Senior Level",
    company: "Salesforce",
    skills: ["Product Management", "Agile Methodology"],
    job_link: "https://www.salesforce.com/company/careers/",
  },
  {
    id: 10,
    postedOn: '2024-01-01',
    title: "DevOps Engineer",
    type: "Full Time",
    location: "In-office",
    experience: "Mid Level",
    company: "IBM",
    skills: ["AWS", "Docker", "Kubernetes"],
    job_link: "https://www.ibm.com/employment/",
  },
  // Add more job entries here
];
